name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: maven

      - name: Maven test
        run: mvn clean test --file pom.xml

      - name: Maven packaging
        run: mvn --batch-mode clean package -DskipTests --file pom.xml

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@v4
